services:
  db_students_postgres:
    image: postgres
    container_name: db_students_postgres
    restart: always
    ports:
      - 4321:5432
    env_file:
      - .env
    volumes:
      - pg_students:/var/lib/postgresql/data
    
  node_students_app:
    container_name: node_students_app
    build: .
    ports:
      - 5001:5000
    depends_on:
      - db_students_postgres
    env_file:
      - .env

volumes:
  pg_students: